version: '3'
services:
  mariadb:
    image: lejianwen/mariadb:1.0.2
    #    build:
    #      context: ./mariadb
    ports:
      - '3307:3306'
    volumes:
      - '/data/mysql_data:/data/mysql_data'
      - '/data/etc/mysql/my.cnf:/etc/my.cnf'