version: '3'
services:
  php-fpm:
    image: lejianwen/php:mini-70fpm-1.2
    #    build:
    #      context: ./miniphp70
    ports:
      - '9000:9000'
    volumes:
      - ${WEB_DATA_DIR}:/data/htdocs
      - ${PHP_CONF_DIR}:/data/apps/php/etc
      - ${PHP_LOG_DIR}:/data/logs/php
    depends_on:
      - mariadb
      - redis
    networks:
      - nmpr
  mariadb:
    image: lejianwen/mariadb:mini-1.3
    ports:
      - '3307:3306'
    volumes:
      - ${MYSQL_DATA_DIR}:/data/mysql_data
      - ${MYSQL_CONF_DIR}/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - nmpr
  nginx:
    image: lejianwen/nginx:mini-lua-1.1.1
    #    build:
    #      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${WEB_DATA_DIR}:/data/htdocs
      - ${NGINX_CONF_DIR}:/data/apps/nginx/conf
      - ${NGINX_LOG_DIR}:/data/logs/nginx
    depends_on:
      - php-fpm
    networks:
      - nmpr
  redis:
    image: lejianwen/redis:mini-1.0
    #    build:
    #      context: ./redis
    command: redis-server /data/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - ${REDIS_CONF_DIR}:/data/etc/redis
      - ${REDIS_LOG_DIR}:/data/logs/redis
      - ${REDIS_DATA_DIR}:/data/redis_data
    networks:
      - nmpr
networks:
  nmpr:
    driver: bridge