version: '3'
services:
  php-fpm:
    image: lejianwen/php:mini-7.4.1
    #    build:
    #      context: ./miniphp70
    #ports:
    #  - '9000:9000'
    environment:
      - TZ=CST-8
    command: php-fpm --nodaemonize --fpm-config /data/apps/php/etc/php-fpm.conf
    volumes:
      - ${WEB_DATA_DIR}:/data/htdocs
      - ${PHP_CONF_DIR}:/data/apps/php/etc
      - ${PHP_LOG_DIR}:/data/logs/php
    depends_on:
      - mariadb
      - redis
    #开启慢日志需要
    cap_add:
      - SYS_PTRACE
    networks:
      - nmpr
  php-cli:
    image: lejianwen/php:mini-7.4.1
    #    build:
    #      context: ./miniphp70
    volumes:
      - ${WEB_DATA_DIR}:/data/htdocs
      - ${PHP_CONF_DIR}:/data/apps/php/etc
      - ${PHP_LOG_DIR}:/data/logs/php
      - ${NGINX_CONF_DIR}:${NGINX_CONF_DIR}
    environment:
      - TZ=CST-8
    depends_on:
      - mariadb
      - redis
    stdin_open: true
    tty: true
    command: /bin/sh # tail -f /dev/null
    networks:
      - nmpr
  mariadb:
    image: lejianwen/mariadb:mini-1.5
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - ${MYSQL_DATA_DIR}:/data/mysql_data
      - ${MYSQL_DUMP_DIR}:/data/mysql_dump
      - ${MYSQL_CONF_DIR}/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=CST-8
    networks:
      - nmpr
  nginx:
    image: lejianwen/nginx:mini-lua-1.1.1
    #    build:
    #      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      - TZ=CST-8
    volumes:
      - ${WEB_DATA_DIR}:/data/htdocs
      - ${NGINX_CONF_DIR}:/data/apps/nginx/conf
      - ${NGINX_LOG_DIR}:/data/logs/nginx
    depends_on:
      - php-fpm
    networks:
      - nmpr
  redis:
    image: lejianwen/redis:mini-1.0
    #    build:
    #      context: ./redis
    command: redis-server /data/etc/redis/redis.conf
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ${REDIS_CONF_DIR}:/data/etc/redis
      - ${REDIS_LOG_DIR}:/data/logs/redis
      - ${REDIS_DATA_DIR}:/data/redis_data
    networks:
      - nmpr
networks:
  nmpr:
    driver: bridge