version: '3'
services:
  mini-70fpm:
    image: lejianwen/php:mini-70fpm
    #    build:
    #      context: ./miniphp70
    ports:
      - '9000:9000'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/php:/data/apps/php/etc'
      - '/data/logs/php:/data/logs/php'
    networks:
      - nmp

networks:
  nmp:
    driver: bridge