version: '3'
services:
  nginx:
    image: nginx:0.1
    #    build:
    #      context: ./mariadb
    ports:
      - '80:80'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/nginx:/data/apps/nginx/conf'
      - '/data/logs/nginx:/data/logs/nginx'