version: '3'
services:
  nginx:
    image: lejianwen/nginx:mini-lua-1.1
    # image: lejianwen/nginx:mini-1.0
    #    build:
    #      context: ./mariadb
    ports:
      - '80:80'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/nginx:/data/apps/nginx/conf'
      - '/data/logs/nginx:/data/logs/nginx'