version: '3'
services:
  php70-fpm:
    image: lejianwen/php:70-swoole-1.0
    #    build:
    #      context: ./php70
    ports:
      - '9000:9000'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/php:/data/apps/php/etc'
      - '/data/logs/php:/data/logs/php'


