version: '3'
services:
  php-fpm:
    image: lejianwen/php:70fpm-mini
    #    build:
    #      context: ./miniphp70
    ports:
      - '9000:9000'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/php:/data/apps/php/etc'
      - '/data/logs/php:/data/logs/php'
    depends_on:
      - mariadb
    networks:
      - nmp
  #  php70-fpm:
  #    image: lejianwen/php:70fpm
  #    #    build:
  #    #      context: ./miniphp70
  #    ports:
  #      - '9001:9000'
  #    volumes:
  #      - '/data/htdocs:/data/htdocs'
  #      - '/data/etc/php:/data/apps/php/etc'
  #      - '/data/logs/php:/data/logs/php'
  #    depends_on:
  #      - mariadb
  #    networks:
  #      - nmp
  mariadb:
    image: lejianwen/mariadb:mini-1.1
    ports:
      - '3307:3306'
    volumes:
      - '/data/mysql_data:/data/mysql_data'
      - '/data/etc/mysql/my.cnf:/etc/my.cnf'
    environment:
      - MYSQL_ROOT_PASSWORD=111111
    networks:
      - nmp
  nginx:
    image: nginx:0.1
    #    build:
    #      context: ./nginx
    ports:
      - '80:80'
    volumes:
      - '/data/htdocs:/data/htdocs'
      - '/data/etc/nginx:/data/apps/nginx/conf'
      - '/data/logs/nginx:/data/logs/nginx'
    depends_on:
      - php-fpm
    networks:
      - nmp
networks:
  nmp:
    driver: bridge